services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/${MONGO_DB}
      - PORT=${PORT}
      - ENVIRONMENT=${ENVIRONMENT}
      - SWAGGER_HOST=${SWAGGER_HOST}
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
